---
# update-motd is installed on debian and ubuntu systems by default and
# all the other software (required by motd scripts) is installed by 
# common-software role.
# 
# you can test motd locally with: run-parts .
- name: Synchronize (also delete removed) motd scripts
  ansible.posix.synchronize:
    src: ./    # note the '/' <-- !!!
    dest: /etc/update-motd.d/
    delete: true
    perms: true
