- name: NGINX
  hosts: main
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx
      vars:
        nginx_install_from: os_repository
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: configure-nginx/main
