- name: Copy logrotate configs
  copy:
    src: "{{ item }}"
    dest: /etc/logrotate.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "*"

- name: Restart logrotate
  ansible.builtin.systemd:
    name: logrotate
    state: restarted
