- name: Install common & useful software
  apt: name={{ item }}
  with_items:
      - gpg
      - git
      - net-tools
      - vim
      - ncdu
      - htop
      - python3
      - python3-pip
      # Required by motd
      - jq
      - curl
      - vnstat
      - rsync # to sync the motd
      # backup software
      - restic