---
- name: Ensure directory for Docker service exists.
  file: "path=/opt/pdns state=directory"

- name: Template docker-compose
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /opt/pdns/docker-compose.yml

- name: Start PowerDNS
  community.docker.docker_compose:
    restarted: true
    project_src: /opt/pdns
