- name: Set MOTD
  hosts: all
  roles:
    - big-motd

- name: Set hostname
  hosts: all
  roles:
    - set-hostname

- name: Install common software
  hosts: all
  roles:
    - common-software

- name: Install docker
  hosts: all
  roles:
    - docker-installation
