- name: Set hostname
  hosts: all
  roles:
    - set-hostname

- name: Install common software
  hosts: all
  roles:
    - common-software

- name: Update and upgrade apt packages
  hosts: all
  roles:
    - update-packages

# has to be after common-software (rsync is installed in common-software)
- name: Set MOTD
  hosts: all
  roles:
    - big-motd

- name: Install docker
  hosts: all
  roles:
    - docker-installation
